worker_processes  1;

events {
    worker_connections  1024;
}

http {
  include       mime.types;
  default_type  application/octet-stream;

  sendfile        on;

  server {
    listen       8080;
    server_name  localhost;

    location / {
      #root /usr/share/nginx/html;
      #rewrite ^(.*)/(core.*)/(.*\.json) /valid.json break;

      rewrite ~*/core/(.*)$ /core/$1 break;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-forward-for $proxy_add_x_forwarded_for;
      proxy_pass http://dochub:3030;
    }
    
    location ~* \.json {
        #root /usr/share/nginx/html;
        #rewrite ^(.*)/(core.*)/(.*\.json) /$3 break;
        rewrite ^(.*)/(core.*)/(.*\.json) /$2 break;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-forward-for $proxy_add_x_forwarded_for;
        proxy_pass http://dochub:3030;
    }
  }

  server {
    listen       8081;
    server_name  localhost;

    location / {
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-forward-for $proxy_add_x_forwarded_for;
      proxy_pass http://dochub:3030;
    }

    location /svg/ {
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-forward-for $proxy_add_x_forwarded_for;
      proxy_pass http://dochub:8079/svg/;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
      root   /usr/share/nginx/html;
    }
  }
}